---
title: "Final_Project"
output: html_notebook
---


```{r}
library(tidytext)
library(dplyr)
library(stringr)
library(readr)
library(ggplot2)
library(textdata)
library(tidyr)
library(topicmodels)
```

```{r}
top_20_reviews <- read_csv("top_20_reviews.csv")
```

```{r}
top_20_reviews
```
```{r}
tidy_titles <- top_20_reviews %>% unnest_tokens(word, clean_text)
```

```{r}
review_sentiments <- tidy_titles %>% 
  inner_join(get_sentiments("bing")) %>%
  count(Title, index = word, sentiment) %>% # ,
  pivot_wider(names_from = sentiment, values_from = n, values_fill = 0) %>%
  mutate(sentiment = positive - negative)
```
```{r}
#for all the book titles grouped together
bing_word_counts <- tidy_titles %>%
  inner_join(get_sentiments("bing")) %>%
  count(word, sentiment, sort = TRUE) %>%
  ungroup()
bing_word_counts
```
```{r}
bing_word_counts %>%
  group_by(sentiment) %>%
  slice_max(n, n = 10) %>% 
  ungroup() %>%
  mutate(word = reorder(word, n)) %>%
  ggplot(aes(n, word, fill = sentiment)) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~sentiment, scales = "free_y") +
  labs(x = "Contribution to sentiment",
       y = NULL)

#this plot shows that overall the reviews seem to be positive
```

```{r}
book_word_counts <- tidy_titles %>%
  inner_join(get_sentiments("bing")) %>%
  group_by(Title) %>%
  count(word, sentiment, sort = TRUE)
book_word_counts
```
```{r}
wuthering_heights <-
 book_word_counts %>%
  filter(Title == "Wuthering Heights") %>%
  group_by(sentiment) %>%
  slice_max(n, n = 10) %>% 
  ungroup() %>%
  mutate(word = reorder(word, n)) %>%
  ggplot(aes(n, word, fill = sentiment)) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~sentiment, scales = "free_y") +
  labs(x = "Contribution to sentiment",
       y = NULL, title = "Wuthering Heights") 
wuthering_heights
```

```{r}
the_giver <-
 book_word_counts %>%
  filter(Title == "The Giver") %>%
  group_by(sentiment) %>%
  slice_max(n, n = 10) %>% 
  ungroup() %>%
  mutate(word = reorder(word, n)) %>%
  ggplot(aes(n, word, fill = sentiment)) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~sentiment, scales = "free_y") +
  labs(x = "Contribution to sentiment",
       y = NULL, title = "The Giver")
the_giver
```

```{r}
 book_word_counts %>%
  filter(Title == "Alice's Adventures in Wonderland") %>%
  group_by(sentiment) %>%
  slice_max(n, n = 10) %>% 
  ungroup() %>%
  mutate(word = reorder(word, n)) %>%
  ggplot(aes(n, word, fill = sentiment)) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~sentiment, scales = "free_y") +
  labs(x = "Contribution to sentiment",
       y = NULL, title = "Alice's Adventures in Wonderland")
```


```{r}
#this works, but the graph is zoomed out too much
sentiment_1984 <- ggplot(review_sentiments %>% filter(Title == "1984"), aes(index, sentiment, fill = Title)) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~Title, ncol = 2, scales = "free_x")
#ggsave("sentiment_graph.pdf", width = 10, height = 20)
sentiment_1984
```

```{r}
## Creating document matrix for the LDA model
dtm <- tidy_titles %>%  count(Title, word) %>%
  cast_dtm(Title, word, n)
dtm
```

```{r}
my_lda <- LDA(dtm, k = 5, control = list(seed = 1234))
my_lda
```

```{r}
#word probabilties
my_topics <- tidy(my_lda, matrix = "beta")
my_topics
```

```{r}
top_terms <- my_topics %>%
  group_by(topic) %>%
  slice_max(beta, n = 10) %>% 
  ungroup() %>%
  arrange(topic, -beta)
```

```{r}
top_terms %>%
  mutate(term = reorder_within(term, beta, topic)) %>%
  ggplot(aes(beta, term, fill = factor(topic))) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~ topic, scales = "free") +
  scale_y_reordered()
```

Repeat process for mid 20 titles
```{r}
mid_20_reviews <- read_csv("/Users/tiffanytra/Downloads/mid_20_reviews.csv")

tidy_titles <- mid_20_reviews %>% unnest_tokens(word, clean_text)

review_sentiments <- tidy_titles %>% 
  inner_join(get_sentiments("bing")) %>%
  count(Title, index = word, sentiment) %>% # ,
  pivot_wider(names_from = sentiment, values_from = n, values_fill = 0) %>%
  mutate(sentiment = positive - negative)

bing_word_counts <- tidy_titles %>%
  inner_join(get_sentiments("bing")) %>%
  count(word, sentiment, sort = TRUE) %>%
  ungroup()

#graph of overall sentiment 
bing_word_counts %>%
  group_by(sentiment) %>%
  slice_max(n, n = 10) %>% 
  ungroup() %>%
  mutate(word = reorder(word, n)) %>%
  ggplot(aes(n, word, fill = sentiment)) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~sentiment, scales = "free_y") +
  labs(x = "Contribution to sentiment",
       y = NULL)

#reviews still overwhelmingly positive
```


